version: '3'
services:
  medic-api:
    container_name: medic-api
    depends_on:
      - db
    build:
      context: app
      dockerfile: ./docker/Dockerfile
    image: medics-api
    env_file:
      - ./app/docker/.env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app

  db:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

